### ISSUE TITLE
Does not work when switch language to server side language.

### ISSUE THREAD

**Issue by devansingaram** [akamuraasai/HackerRankAPI#1]
Hey mate, thanks for doing this code.

It works great when set the hacker rank language to javascript.

However has issues when set hacker rank language to a server side like php, it just spits back the code.

any ideas on how to resolve?

**Comment by akamuraasai** [comment]
Hi @devansingaram ,
I've added some new examples that might be useful for you, I've used some backend languages, and I've also created some new functions to dynamically acquire the language code.

[PHP Example](https://github.com/akamuraasai/HackerRankAPI/blob/master/examples/test_api_php.php)
[Python Example](https://github.com/akamuraasai/HackerRankAPI/blob/master/examples/test_api_python.php)

And here is a snippet for PHP usage:
```php
<?
...
$caller = new HRCaller();
$code = '<?php

        $handle = fopen ("php://stdin","r");
        fscanf($handle,"%d",$n);
        $arr_temp = fgets($handle);
        $arr = explode(" ",$arr_temp);
        array_walk($arr,\'intval\');
        
        $result = 0;
        foreach ($arr as $item) 
            $result += $item;
        echo $result;
        
        ?>';

$language = 7; //PHP
```

Hope this helps you. I'm closing this issue for now.
Best regards.
